name: dunfell-agl

on:
  pull_request:
    types: [ opened, synchronize, reopened, closed ]
  release:
    types: [ published, created, edited ]
  workflow_dispatch:
  schedule:
    # daily
    - cron:  '0 0 * * *'

jobs:

  master-qemu:
  
    env:
      MACHINE: qemux86-64
      AGL_BRANCH: master

    runs-on: [self-hosted, linux]
    
    container:
      image: ghcr.io/meta-flutter/ubuntu-20-dev:main
      options:
        --user 1018
        --storage-opt overlay.mount_program=/usr/bin/fuse-overlayfs
        --storage-opt overlay.mountopt=nodev,metacopy=on,noxattrs=1
        -v /b/github-ci/download:/home/dev/dl:Z
        -v /b/github-ci/sstate/agl/qemu:/home/dev/sstate:Z
        -v /b/github-ci/artifacts/agl/qemu:/home/dev/artifacts:Z
      
    steps:
    
      - name: Display UID Info
        run: |
          whoami
          id -u
          
      - name: Set Ownership
        run: |
          chown -R dev:dev $HOME .
          
      - uses: actions/checkout@v2

      - name: Fetch Layers
        run: |
          [ -d ../agl-master-qemu ] || mkdir -p ../agl-master-qemu
          cd ../agl-master-qemu
          rm -rf .repo  bsp  external  meta-agl  meta-agl-demo  meta-agl-devel  meta-agl-flutter
          /home/dev/bin/repo init -b ${{ env.AGL_BRANCH }} -u https://gerrit.automotivelinux.org/gerrit/AGL/AGL-repo --no-clone-bundle
          /home/dev/bin/repo sync --no-clone-bundle -j `grep -c ^processor /proc/cpuinfo` &
          wait
          cd meta-agl-devel
          git fetch "https://gerrit.automotivelinux.org/gerrit/AGL/meta-agl-devel" refs/changes/68/26868/14 && git checkout FETCH_HEAD
          cd ../external/meta-flutter
          git checkout dunfell
          git pull
          
      - name: Configure AGL build
        shell: bash
        working-directory: ../agl-master-qemu
        run: |
          rm -rf build/conf
          . ./meta-agl/scripts/aglsetup.sh -m ${{ env.MACHINE }} agl-devel agl-basesystem agl-flutter
          echo '***************************************'
          echo 'INHERIT += "rm_work"' >> ./conf/local.conf
          echo 'DL_DIR = "/home/dev/dl"' >> ./conf/local.conf
          echo 'SSTATE_DIR = "/home/dev/sstate"' >> ./conf/local.conf
          echo 'SSTATE_MIRRORS = "file://.* file:///home/dev/sstate/PATH"' >> ./conf/local.conf
          echo 'SSTATE_MIRRORS += "file://.* http://download.automotivelinux.org/sstate-mirror/${{ env.AGL_BRANCH }}/${DEFAULTTUNE}/PATH;downloadfilename=PATH"' >> ./conf/local.conf
          echo 'INHERIT:remove = "uninative"' >> ./conf/local.conf
          echo 'INSANE_SKIP_${PN} += "host-user-contaminated"' >> ../external/meta-clang/recipes-devtools/clang/clang_git.bb
          echo '** Layers *****************************'
          bitbake-layers add-layer ../external/meta-clang
          bitbake-layers show-layers
          echo '** Kernel *****************************'
          bitbake -e virtual/kernel | grep "^PV"
          bitbake -e virtual/kernel | grep "^PN"
          echo '***************************************'
          bitbake -e > bb.environment

      - name: Build agl-image-flutter
        shell: bash
        working-directory: ../agl-master-qemu
        run: |
          . ./build/agl-init-build-env
          rm -rf /home/dev/artifacts/*
          bitbake flutter-sdk -c do_cleansstate
          bitbake flutter-sdk-native -c do_cleansstate
          bitbake flutter-engine -c do_cleansstate
          bitbake agl-image-flutter
          cp bb.environment /home/dev/artifacts
          cp tmp/deploy/images/qemux86-64/agl-image-flutter-qemux86-64.wic.vmdk /home/dev/artifacts
          cp tmp/deploy/images/qemux86-64/agl-image-flutter-qemux86-64.ext4 /home/dev/artifacts
          cp tmp/deploy/images/qemux86-64/bzImage /home/dev/artifacts

      - name: Publish agl-image-flutter artifacts
        uses: actions/upload-artifact@v2
        with:
          name: agl-image-flutter-qemux86-64-linux
          path: |
             /home/dev/artifacts/*

      - name: Build agl-image-flutter SDK
        shell: bash
        working-directory: ../agl-master-qemu
        run: |
          . ./build/agl-init-build-env
          rm -rf /home/dev/artifacts/*
          bitbake agl-image-flutter -c do_populate_sdk
          cp bb.environment /home/dev/artifacts
          cp tmp/deploy/sdk/poky-agl-*.sh /home/dev/artifacts

      - name: Publish agl-image-flutter SDK artifact
        uses: actions/upload-artifact@v2
        with:
          name: agl-image-flutter-sdk-qemux86-64-linux
          path: |
             /home/dev/artifacts/*
