
name: dunfell-nvidia-jetson-xavier-nx-devkit

on:
  pull_request:
    types: [ opened, synchronize, reopened, closed ]
  release:
    types: [ published, created, edited ]
  workflow_dispatch:
  schedule:
    # daily
    - cron:  '0 0 * * *'

jobs:

  dunfell-nvidia-jetson-xavier-nx-devkit:
  
    env:
      YOCTO_BRANCH: dunfell
      DEMO_BRANCH: dunfell-l4t-r32.5.0
      MACHINE: jetson-xavier-nx-devkit
      DISTRO: tegrademo
      
    runs-on: [self-hosted, linux]
    
    container:
      image: ghcr.io/meta-flutter/ubuntu-18-dev:main
      options:
        --user 1018
        --storage-opt overlay.mount_program=/usr/bin/fuse-overlayfs
        --storage-opt overlay.mountopt=nodev,metacopy=on,noxattrs=1
        -v /mnt/raid10/github-ci/download:/home/dev/dl:Z
        -v /mnt/raid10/github-ci/sstate/yocto/dunfell/nvidia-jetson-xavier-nx-devkit:/home/dev/sstate:Z
        -v /mnt/raid10/github-ci/artifacts/nvidia-jetson-xavier-nx-devkit:/home/dev/artifacts:Z
        -v /mnt/raid10/github-ci/nvidia:/home/dev/devnet:Z


    steps:
    
      - name: Display UID Info
        run: |
          whoami
          id -u
          
      - name: Set Ownership
        run: |
          chown -R dev:dev $HOME .
          
      - uses: actions/checkout@v2
        with:
          path: ''

      - name: Fetch Source
        run: |
          [ -d ../${{ env.MACHINE }} ] || mkdir -p ../${{ env.MACHINE }}
          cd ../${{ env.MACHINE }}
          [ -d tegra-demo-distro ] || git clone -b ${{ env.DEMO_BRANCH }} --single-branch https://github.com/OE4T/tegra-demo-distro.git
          cd tegra-demo-distro
          git pull
          git submodule update --init
          cd repos
          rm -rf meta-clang meta-vulkan meta-flutter-plugins || true
          git clone -b dunfell-clang12 --single-branch https://github.com/kraj/meta-clang.git &
          git clone -b dunfell-no-mesa --single-branch https://github.com/jwinarske/meta-vulkan.git &
          git clone -b jw/plugin-examples --single-branch https://github.com/meta-flutter/meta-flutter-plugins &
          wait
          cd ../layers
          rm -rf meta-flutter meta-clang meta-vulkan meta-flutter-plugins || true
          ln -sf ../repos/meta-clang meta-clang
          ln -sf ../repos/meta-vulkan meta-vulkan
          ln -sf ../repos/meta-flutter-plugins meta-flutter-plugins
          ln -sf ../../../meta-flutter meta-flutter
          cd ..

      - name: Configure build
        shell: bash
        working-directory: ../${{ env.MACHINE }}/tegra-demo-distro
        run: |
          env
          WORKSPACE=`pwd`
          rm -rf build/conf || true
          . ./setup-env --machine ${{ env.MACHINE }}
          sed -i '/MACHINE ??=/d' ./conf/local.conf
          sed -i '/DISTRO ?=/d' ./conf/local.conf
          sed -i '/NVIDIA_DEVNET_MIRROR/d' ./conf/local.conf
          sed -i "/GLIBC_GENERATE_LOCALES/d" ./conf/local.conf
          sed -i "/IMAGE_LINGUAS/d" ./conf/local.conf
          echo "MACHINE ??= \"${{ env.MACHINE }}\"" >> ./conf/local.conf
          echo "DISTRO ?= \"${{ env.DISTRO }}\"" >> ./conf/local.conf
          echo 'NVIDIA_DEVNET_MIRROR ?= "file:///home/dev/devnet"' >> ./conf/local.conf
          echo '***************************************'
          echo 'INHERIT += "rm_work"' >> ./conf/local.conf
          echo 'DL_DIR = "/home/dev/dl"' >> ./conf/local.conf
          echo 'SSTATE_DIR = "/home/dev/sstate"' >> ./conf/local.conf
          echo 'SSTATE_MIRRORS = "file://.* file:///home/dev/sstate/PATH"' >> ./conf/local.conf
          echo 'DISTRO_FEATURES_append = " vulkan"' >> ./conf/local.conf
          echo 'DISTRO_FEATURES_remove = "x11"' >> ./conf/local.conf
          echo 'GLIBC_GENERATE_LOCALES = "en_US.UTF-8"' >> ./conf/local.conf
          echo 'IMAGE_LINGUAS = "en-us"' >> ./conf/local.conf
          echo 'FLUTTER_SDK_TAG = "2.10.2"' >> ./conf/local.conf
          echo 'CLANGSDK = "1"' >> ./conf/local.conf
          echo 'CORE_IMAGE_BASE_INSTALL_remove = " packagegroup-demo-vulkantests"' >> ./conf/local.conf
          echo 'CORE_IMAGE_BASE_INSTALL_remove = " packagegroup-demo-westontests"' >> ./conf/local.conf
          echo 'CORE_IMAGE_BASE_INSTALL_append = " vulkan-tools"' >> ./conf/local.conf
          echo 'CORE_IMAGE_BASE_INSTALL_append = " libdrm-tests"' >> ./conf/local.conf
          echo 'PACKAGECONFIG_pn-sascha-samples = "wayland"' >> ./conf/local.conf
          echo 'TEGRAFLASH_SDCARD_SIZE = "32G"' >> ./conf/local.conf
          echo 'KERNEL_ARGS_append = " quiet"' >> ./conf/local.conf
          echo 'PREFERRED_VERSION_libserialport = "6f9b03e"' >> ./conf/local.conf
          echo 'PREFERRED_VERSION:gstreamer1.0 = "1.16%"' >> ./conf/local.conf
          echo 'PREFERRED_VERSION:gstreamer1.0-libav = "1.16%"' >> ./conf/local.conf
          echo 'PREFERRED_VERSION:gstreamer1.0-plugins-bad = "1.16%"' >> ./conf/local.conf
          echo 'PREFERRED_VERSION:gstreamer1.0-plugins-good = "1.16%"' >> ./conf/local.conf
          echo 'PREFERRED_VERSION:gstreamer1.0-plugins-ugly = "1.16%"' >> ./conf/local.conf
          echo 'PREFERRED_VERSION:gstreamer1.0-plugins-base = "1.16%"' >> ./conf/local.conf
          echo 'PACKAGECONFIG:remove:pn-gstreamer1.0-plugins-bad = "vulkan"' >> ./conf/local.conf
          echo 'CORE_IMAGE_BASE_INSTALL_append = " \
              gstreamer1.0-libav \
              gstreamer1.0-plugins-bad \
              gstreamer1.0-plugins-good \
              gstreamer1.0-plugins-ugly \
              "' >> ./conf/local.conf
          echo 'INHIBIT_PACKAGE_DEBUG_SPLIT = "1"' >> ./conf/local.conf
          echo 'LICENSE_FLAGS_WHITELIST = "commercial"' >> ./conf/local.conf
          echo '********** ./conf/local.conf **********'
          cat ./conf/local.conf
          echo '***************************************'
          bitbake-layers add-layer \
            ${RUNNER_WORKSPACE}/${{ env.MACHINE }}/tegra-demo-distro/layers/meta-flutter \
            $WORKSPACE/layers/meta-clang \
            $WORKSPACE/layers/meta-vulkan \
            $WORKSPACE/layers/meta-flutter-plugins
          bitbake-layers show-layers
          echo '***************************************'

      - name: Build Base Image
        shell: bash
        working-directory: ../${{ env.MACHINE }}/tegra-demo-distro
        run: |
          . ./setup-env
          bitbake gstreamer1.0-plugins-bad -c do_cleansstate
          bitbake demo-image-weston
          rm -rf /home/dev/artifacts/*

      - name: Build sascha-samples (Wayland)
        shell: bash
        working-directory: ../${{ env.MACHINE }}/tegra-demo-distro
        run: |
          . ./setup-env
          bitbake sascha-samples
          rm -rf /home/dev/artifacts/*
          cp tmp/deploy/rpm/aarch64/sascha-samples-git*.rpm /home/dev/artifacts

      - name: Publish sascha-samples artifacts
        uses: actions/upload-artifact@v2
        with:
          name: sascha-samples-wayland-jetson-nano-devkit
          path: |
             /home/dev/artifacts/*.rpm

      - name: Build flutter-engine-debug
        shell: bash
        working-directory: ../${{ env.MACHINE }}/tegra-demo-distro
        run: |
          . ./setup-env
          bitbake flutter-engine-debug -c do_cleansstate
          bitbake flutter-engine-debug
          rm -rf /home/dev/artifacts/*
          cp tmp/deploy/rpm/aarch64/flutter-engine-debug-git*.rpm /home/dev/artifacts

      - name: Publish flutter-engine-debug artifacts
        uses: actions/upload-artifact@v2
        with:
          name: flutter-engine-debug-jetson-nano-devkit
          path: |
             /home/dev/artifacts/*.rpm
      
      - name: Build ivi-homescreen-debug
        shell: bash
        working-directory: ../${{ env.MACHINE }}/tegra-demo-distro
        run: |
          . ./setup-env
          bitbake ivi-homescreen-debug -c do_cleansstate
          bitbake ivi-homescreen-debug
          rm -rf /home/dev/artifacts/*
          cp tmp/deploy/rpm/aarch64/ivi-homescreen-debug-git*.rpm /home/dev/artifacts

      - name: Publish ivi-homescreen-debug artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ivi-homescreen-debug-jetson-nano-devkit
          path: |
             /home/dev/artifacts/*.rpm

      - name: Build flutter-engine-profile
        shell: bash
        working-directory: ../${{ env.MACHINE }}/tegra-demo-distro
        run: |
          . ./setup-env
          bitbake flutter-engine-profile -c do_cleansstate
          bitbake flutter-engine-profile
          rm -rf /home/dev/artifacts/*
          cp tmp/deploy/rpm/aarch64/flutter-engine-profile-git*.rpm /home/dev/artifacts

      - name: Publish flutter-engine-profile artifacts
        uses: actions/upload-artifact@v2
        with:
          name: flutter-engine-profile-jetson-nano-devkit
          path: |
             /home/dev/artifacts/*.rpm

      - name: Build flutter-engine-release
        shell: bash
        working-directory: ../${{ env.MACHINE }}/tegra-demo-distro
        run: |
          . ./setup-env
          bitbake flutter-engine-release -c do_cleansstate
          bitbake flutter-engine-release
          rm -rf /home/dev/artifacts/*
          cp tmp/deploy/rpm/aarch64/flutter-engine-release-git*.rpm /home/dev/artifacts

      - name: Publish flutter-engine-release artifacts
        uses: actions/upload-artifact@v2
        with:
          name: flutter-engine-release-jetson-nano-devkit
          path: |
             /home/dev/artifacts/*.rpm

      - name: Build flutter-gallery-debug
        shell: bash
        working-directory: ../${{ env.MACHINE }}/tegra-demo-distro
        run: |
          . ./setup-env
          bitbake flutter-sdk-native -c do_cleansstate
          bitbake flutter-gallery-debug -c do_cleansstate
          bitbake flutter-gallery-debug
          rm -rf /home/dev/artifacts/*
          cp tmp/deploy/rpm/aarch64/flutter-gallery-debug-git*.rpm /home/dev/artifacts
      
      - name: Publish flutter-gallery-debug artifacts
        uses: actions/upload-artifact@v2
        with:
          name: flutter-gallery-debug-jetson-nano-devkit
          path: |
             /home/dev/artifacts/*.rpm

      - name: Build flutter-gallery-release
        shell: bash
        working-directory: ../${{ env.MACHINE }}/tegra-demo-distro
        run: |
          . ./setup-env
          bitbake flutter-sdk-native -c do_cleansstate
          bitbake flutter-gallery-release -c do_cleansstate
          bitbake flutter-gallery-release
          rm -rf /home/dev/artifacts/*
          cp tmp/deploy/rpm/aarch64/flutter-gallery-release-git*.rpm /home/dev/artifacts
      
      - name: Publish flutter-gallery-release artifacts
        uses: actions/upload-artifact@v2
        with:
          name: flutter-gallery-release-jetson-nano-devkit
          path: |
             /home/dev/artifacts/*.rpm

      - name: Build Image with Flutter
        shell: bash
        working-directory: ../${{ env.MACHINE }}/tegra-demo-distro
        run: |
          . ./setup-env
          echo 'IMAGE_INSTALL_append = " \
              flutter-engine-debug \
              packagegroup-flutter-plugin-examples-debug \
              flutter-gallery-debug \
              ivi-homescreen-debug \
              sascha-samples \
              "' >> ./conf/local.conf
          bitbake demo-image-weston
          rm -rf /home/dev/artifacts/*
          cp tmp/deploy/images/${{ env.MACHINE }}/demo-image-weston-${{ env.MACHINE }}-*.tegraflash.tar.gz /home/dev/artifacts

      - name: Publish bootable SD card image
        uses: actions/upload-artifact@v2
        with:
          name: demo-image-weston-${{ env.MACHINE }}-flutter-sdimage
          path: |
             /home/dev/artifacts/*
