name: honister-rpi3-64

on:
  pull_request:
    types: [ opened, synchronize, reopened, closed ]
  release:
    types: [ published, created, edited ]
  workflow_dispatch:
  schedule:
    # daily
    - cron:  '0 0 * * *'

jobs:

  honister-rpi3-drm:
  
    env:
      DISTRO_VERSION: 3.4.2
      YOCTO_BRANCH: honister
      MACHINE: raspberrypi3-64
      
    runs-on: [self-hosted, linux]
    
    container:
      image: ghcr.io/meta-flutter/ubuntu-20-dev:main
      options:
        --user 1018
        --storage-opt overlay.mount_program=/usr/bin/fuse-overlayfs
        --storage-opt overlay.mountopt=nodev,metacopy=on,noxattrs=1
        -v /mnt/raid10/github-ci/download:/home/dev/dl:Z
        -v /mnt/raid10/github-ci/sstate/yocto/honister/rpi3-drm/latest:/home/dev/sstate:Z
        -v /mnt/raid10/github-ci/artifacts/rpi3/drm:/home/dev/artifacts:Z


    steps:
    
      - name: Display UID Info
        run: |
          whoami
          id -u
          
      - name: Set Ownership
        run: |
          chown -R dev:dev $HOME .
          
      - uses: actions/checkout@v2
        with:
          path: ''

      - name: Fetch poky
        run: |
          [ -d ../rpi3-drm-honister-latest ] || mkdir -p ../rpi3-drm-honister-latest
          cd ../rpi3-drm-honister-latest
          rm -rf sources || true
          ls -la
          git config --list
          git config --global user.email joel@winarske@gmail.com
          git config --global user.name "Joel Winarske"
          git config --list
          /home/dev/bin/repo init -u https://github.com/jwinarske/manifests.git -m rpi64.xml -b $YOCTO_BRANCH
          /home/dev/bin/repo sync --force-sync --no-clone-bundle -j `grep -c ^processor /proc/cpuinfo` &
          wait

      - name: Configure build
        shell: bash
        working-directory: ../rpi3-drm-honister-latest
        run: |
          rm -rf ${{ env.MACHINE }}/conf || true
          . ./setup-environment ${{ env.MACHINE }}
          echo '***************************************'
          echo -e 'DL_DIR = "/home/dev/dl"' >> ./conf/local.conf
          echo -e 'SSTATE_DIR = "/home/dev/sstate"' >> ./conf/local.conf
          echo -e 'SSTATE_MIRRORS = "file://.* file:///home/dev/sstate/PATH"' >> ./conf/local.conf
          echo -e 'SSTATE_MIRRORS += "file://.* http://sstate.yoctoproject.org/${{ env.DISTRO_VERSION }}/PATH;downloadfilename=PATH"' >> ./conf/local.conf
          echo -e 'IMAGE_LINGUAS = "en-us"' >> ./conf/local.conf
          echo -e 'PACKAGECONFIG:pn-vkcube = "kms wayland"' >> ./conf/local.conf
          echo -e 'FLUTTER_SDK_TAG = "2.10.2"' >> ./conf/local.conf
          echo -e 'PREFERRED_PROVIDER:jpeg = "libjpeg-turbo"' >> ./conf/local.conf
          echo -e 'PREFERRED_PROVIDER:jpeg-native = "libjpeg-turbo-native"' >> ./conf/local.conf
          echo -e '' >> ./conf/local.conf
          echo -e 'PREFERRED_VERSION:vulkan-headers = "1.2.198.0"' >> ./conf/local.conf
          echo -e 'PREFERRED_VERSION:vulkan-loader = "1.2.198.1"' >> ./conf/local.conf
          echo -e 'PREFERRED_VERSION:vulkan-tools = "1.2.198.0"' >> ./conf/local.conf
          echo -e 'PREFERRED_VERSION:glslang = "11.6.0"' >> ./conf/local.conf
          echo -e 'PREFERRED_VERSION:vulkan-validationlayers = "1.2.198"' >> ./conf/local.conf
          echo '********** ./conf/local.conf **********'
          cat ./conf/local.conf
          echo '***************************************'
          bitbake-layers remove-layer meta-flutter
          bitbake-layers add-layer ../../meta-flutter
          bitbake-layers show-layers
          echo '***************************************'
          bitbake -e virtual/kernel | grep "^PV"
          bitbake -e virtual/kernel | grep "^PN"
          echo '***************************************'
          bitbake -e core-image-minimal | grep "^DISTRO_FEATURES"
          echo '***************************************'
          bitbake -e > bb.environment

      - name: Build core-image-minimal
        shell: bash
        working-directory: ../rpi3-drm-honister-latest
        run: |
          . ./sources/poky/oe-init-build-env ${{ env.MACHINE }}
          bitbake core-image-minimal

      - name: Build swiftshader
        shell: bash
        working-directory: ../rpi3-drm-honister-latest
        run: |
          . ./sources/poky/oe-init-build-env ${{ env.MACHINE }}
          bitbake swiftshader
          rm -rf /home/dev/artifacts/*
          cp tmp/deploy/rpm/cortexa53/swiftshader-git*.rpm /home/dev/artifacts

      - name: Publish swiftshader artifacts
        uses: actions/upload-artifact@v2
        with:
          name: swiftshader-rpi3-64
          path: |
             /home/dev/artifacts/*.rpm

      - name: Build flutter-engine-release
        shell: bash
        working-directory: ../rpi3-drm-honister-latest
        run: |
          . ./sources/poky/oe-init-build-env ${{ env.MACHINE }}
          bitbake flutter-engine-release -c do_cleansstate
          bitbake flutter-engine-release
          rm -rf /home/dev/artifacts/*
          cp tmp/deploy/rpm/cortexa53/flutter-engine-release-git*.rpm /home/dev/artifacts

      - name: Publish flutter-engine-release artifacts
        uses: actions/upload-artifact@v2
        with:
          name: flutter-engine-release-rpi3-64
          path: |
             /home/dev/artifacts/*.rpm

      - name: Build flutter-pi-release
        shell: bash
        working-directory: ../rpi3-drm-honister-latest
        run: |
          . ./sources/poky/oe-init-build-env ${{ env.MACHINE }}
          bitbake flutter-pi-release
          rm -rf /home/dev/artifacts/*
          cp tmp/deploy/rpm/cortexa53/flutter-pi-release-git*.rpm /home/dev/artifacts

      - name: Publish flutter-pi-release artifacts
        uses: actions/upload-artifact@v2
        with:
          name: flutter-pi-release-rpi3-64
          path: |
             /home/dev/artifacts/*.rpm

      - name: Build flutter-gallery-release
        shell: bash
        working-directory: ../rpi3-drm-honister-latest
        run: |
          . ./sources/poky/oe-init-build-env ${{ env.MACHINE }}
          bitbake flutter-sdk-native -c do_cleansstate
          bitbake flutter-gallery-release -c do_cleansstate
          bitbake flutter-gallery-release
          rm -rf /home/dev/artifacts/*
          cp tmp/deploy/rpm/cortexa53/flutter-gallery-release-git*.rpm /home/dev/artifacts

      - name: Publish flutter-gallery-release artifacts
        uses: actions/upload-artifact@v2
        with:
          name: flutter-gallery-release-rpi3-64
          path: |
             /home/dev/artifacts/*.rpm

      - name: Build core-image-minimal
        shell: bash
        working-directory: ../rpi3-drm-honister-latest
        run: |
          . ./sources/poky/oe-init-build-env ${{ env.MACHINE }}
          echo 'CORE_IMAGE_EXTRA_INSTALL:append = " \
              flutter-pi-release \
              flutter-gallery-release \
              swiftshader \
              sascha-samples \
              vkcube \
              vkquake3 \
              vkrunner \
              vk-layer-perfdoc \
              "' >> ./conf/local.conf
          bitbake core-image-minimal
          rm -rf /home/dev/artifacts/*
          cp bb.environment /home/dev/artifacts
          cp tmp/deploy/images/raspberrypi3-64/core-image-minimal-raspberrypi3-64.wic.bmap /home/dev/artifacts
          cp tmp/deploy/images/raspberrypi3-64/core-image-minimal-raspberrypi3-64.wic.bz2 /home/dev/artifacts

      - name: Publish SD card image artifact
        uses: actions/upload-artifact@v2
        with:
          name: rpi3-drm-flutter-release-honister-sdimage
          path: |
             /home/dev/artifacts/*
