name: kirkstone-rpi-zero2w-64

on:
  pull_request:
    types: [ opened, synchronize, reopened, closed ]
  release:
    types: [ published, created, edited ]
  workflow_dispatch:
  schedule:
    # daily
    - cron:  '0 0 * * *'

jobs:

  weston-release:
  
    env:
      YOCTO_BRANCH: "kirkstone"
      MACHINE: raspberrypi0-2w-64
      RUNTIME: "release"
      
    runs-on: [self-hosted, linux]
    
    container:
      image: ghcr.io/meta-flutter/ubuntu-20-dev:main
      options:
        --user 1018
        --storage-opt overlay.mount_program=/usr/bin/fuse-overlayfs
        --storage-opt overlay.mountopt=nodev,metacopy=on,noxattrs=1
        -v /mnt/raid10/github-ci/download:/home/dev/dl:Z
        -v /mnt/raid10/github-ci/sstate/yocto/kirkstone/zero2w-drm/latest:/home/dev/sstate:Z
        -v /mnt/raid10/github-ci/artifacts/zero2w/drm:/home/dev/artifacts:Z

    steps:
    
      - name: Display UID Info
        run: |
          whoami
          id -u
          
      - name: Set Ownership
        run: |
          chown -R dev:dev $HOME .
          
      - uses: actions/checkout@v2
        with:
          path: ''

      - name: Fetch poky
        run: |
          [ -d ../zero2w-drm-kirkstone-latest ] || mkdir -p ../zero2w-drm-kirkstone-latest
          cd ../zero2w-drm-kirkstone-latest
          rm -rf sources || true
          git config --global user.name "Joel Winarske"
          git config --global user.email joel@winarske@gmail.com
          /home/dev/bin/repo init -u https://github.com/jwinarske/manifests.git -m rpi64.xml -b $YOCTO_BRANCH
          /home/dev/bin/repo sync --force-sync --no-clone-bundle -j `grep -c ^processor /proc/cpuinfo` &
          wait

      - name: Configure build
        shell: bash
        working-directory: ../zero2w-drm-kirkstone-latest
        run: |
          rm -rf ${{ env.MACHINE }}/conf || true
          . ./setup-environment ${{ env.MACHINE }}
          echo '***************************************'
          echo 'DL_DIR = "/home/dev/dl"' >> ./conf/local.conf
          echo 'SSTATE_DIR = "/home/dev/sstate"' >> ./conf/local.conf
          echo 'SSTATE_MIRRORS = "file://.* file:///home/dev/sstate/PATH"' >> ./conf/local.conf
          echo 'ENABLE_BINARY_LOCALE_GENERATION = "1"' >> ./conf/local.conf
          echo 'GLIBC_GENERATE_LOCALES:append = " en_US.UTF-8 es_US.UTF-8 en_GB.UTF-8"' >> ./conf/local.conf
          echo 'IMAGE_LINGUAS:append = " en-us en-gb es-us"' >> ./conf/local.conf
          echo 'DEFAULT_TIMEZONE = "America/Los_Angeles"' >> ./conf/local.conf
          echo 'PACKAGECONFIG:append:pn-ffmpeg = " openssl"' >> ./conf/local.conf
          echo 'PACKAGECONFIG:append:pn-weston = " remoting"' >> ./conf/local.conf
          echo 'IMAGE_INSTALL:append = "\
              default-language-en-us-utf8 \
              tzdata-americas \
              tzdata-core \
              flutter-auto-runtime${{ env.RUNTIME }} \
              flutter-pi-runtime${{ env.RUNTIME }} \
              flutter-gallery-runtime${{ env.RUNTIME }} \
              flutter-test-secure-storage-runtime${{ env.RUNTIME }} \
              flutter-test-video-player-runtime${{ env.RUNTIME }} \
              flutter-test-plugins-runtime${{ env.RUNTIME }} \
              flutter-test-texture-egl-runtime${{ env.RUNTIME }} \
              flutter-test-localization-runtime${{ env.RUNTIME }} \
              flutter-test-membrane-runtime${{ env.RUNTIME }} \
              flutter-test-frb-runtime${{ env.RUNTIME }} \
              "' >> ./conf/local.conf
          echo 'LICENSE_FLAGS_ACCEPTED += " commercial"' >> ./conf/local.conf
          echo '********** ./conf/local.conf **********'
          cat ./conf/local.conf
          echo '***************************************'
          bitbake-layers show-layers
          bitbake-layers remove-layer meta-flutter
          bitbake-layers add-layer ../../meta-flutter
          bitbake-layers show-layers
          echo '***************************************'
          bitbake -e virtual/kernel | grep "^PV"
          bitbake -e virtual/kernel | grep "^PN"
          echo '***************************************'
          bitbake -e rpi-image-flutter-wayland-${{ env.RUNTIME }} | grep "^DISTRO_FEATURES"
          bitbake -e rpi-image-flutter-wayland-${{ env.RUNTIME }} | grep "^IMAGE_FEATURES"
          echo '***************************************'
          bitbake -e > bb.environment
          bitbake -c do_cleansstate flutter-engine-runtime${{ env.RUNTIME }}
          bitbake -c do_cleansstate flutter-gallery-runtime${{ env.RUNTIME }}
          bitbake -c do_cleansstate flutter-test-plugins-runtime${{ env.RUNTIME }}
          bitbake -c do_cleansstate flutter-test-secure-storage-runtime${{ env.RUNTIME }}
          bitbake -c do_cleansstate flutter-test-texture-egl-runtime${{ env.RUNTIME }}
          bitbake -c do_cleansstate flutter-test-video-player-runtime${{ env.RUNTIME }}
          bitbake -c do_cleansstate flutter-test-localization-runtime${{ env.RUNTIME }}
          bitbake -c do_cleansstate flutter-test-membrane-runtime${{ env.RUNTIME }}
          bitbake -c do_cleansstate membrane-example
          bitbake -c do_cleansstate membrane-example-native
          bitbake -c do_cleansstate flutter-test-membrane-runtime${{ env.RUNTIME }}
          bitbake -c do_cleansstate flutter-rust-bridge-example
          bitbake -c do_cleansstate flutter-test-frb-runtime${{ env.RUNTIME }}

      - name: Build rpi-image-weston-flutter-runtimerelease
        shell: bash
        working-directory: ../zero2w-drm-kirkstone-latest
        run: |
          . ./sources/poky/oe-init-build-env ${{ env.MACHINE }}
          bitbake rpi-image-flutter-wayland-${{ env.RUNTIME }}
          rm -rf /home/dev/artifacts/*
          cp bb.environment /home/dev/artifacts
          cp tmp/deploy/images/raspberrypi0-2w-64/rpi-image-flutter-wayland-${{ env.RUNTIME }}-raspberrypi0-2w-64.wic.bmap /home/dev/artifacts
          cp tmp/deploy/images/raspberrypi0-2w-64/rpi-image-flutter-wayland-${{ env.RUNTIME }}-raspberrypi0-2w-64.wic.bz2 /home/dev/artifacts

      - name: Publish SD card image artifact
        uses: actions/upload-artifact@v2
        with:
          name: raspberrypi0-2w-64-weston-flutter-runtime${{ env.RUNTIME }}-sdimage
          path: |
             /home/dev/artifacts/*

  weston-profile:
  
    env:
      YOCTO_BRANCH: "kirkstone"
      MACHINE: raspberrypi0-2w-64
      RUNTIME: "profile"
      
    runs-on: [self-hosted, linux]
    
    container:
      image: ghcr.io/meta-flutter/ubuntu-20-dev:main
      options:
        --user 1018
        --storage-opt overlay.mount_program=/usr/bin/fuse-overlayfs
        --storage-opt overlay.mountopt=nodev,metacopy=on,noxattrs=1
        -v /mnt/raid10/github-ci/download:/home/dev/dl:Z
        -v /mnt/raid10/github-ci/sstate/yocto/kirkstone/zero2w-drm/latest:/home/dev/sstate:Z
        -v /mnt/raid10/github-ci/artifacts/zero2w/drm:/home/dev/artifacts:Z

    steps:
    
      - name: Display UID Info
        run: |
          whoami
          id -u
          
      - name: Set Ownership
        run: |
          chown -R dev:dev $HOME .
          
      - uses: actions/checkout@v2
        with:
          path: ''

      - name: Fetch poky
        run: |
          [ -d ../zero2w-drm-kirkstone-latest ] || mkdir -p ../zero2w-drm-kirkstone-latest
          cd ../zero2w-drm-kirkstone-latest
          rm -rf sources || true
          git config --global user.name "Joel Winarske"
          git config --global user.email joel@winarske@gmail.com
          /home/dev/bin/repo init -u https://github.com/jwinarske/manifests.git -m rpi64.xml -b $YOCTO_BRANCH
          /home/dev/bin/repo sync --force-sync --no-clone-bundle -j `grep -c ^processor /proc/cpuinfo` &
          wait

      - name: Configure build
        shell: bash
        working-directory: ../zero2w-drm-kirkstone-latest
        run: |
          rm -rf ${{ env.MACHINE }}/conf || true
          . ./setup-environment ${{ env.MACHINE }}
          echo '***************************************'
          echo 'DL_DIR = "/home/dev/dl"' >> ./conf/local.conf
          echo 'SSTATE_DIR = "/home/dev/sstate"' >> ./conf/local.conf
          echo 'SSTATE_MIRRORS = "file://.* file:///home/dev/sstate/PATH"' >> ./conf/local.conf
          echo 'ENABLE_BINARY_LOCALE_GENERATION = "1"' >> ./conf/local.conf
          echo 'GLIBC_GENERATE_LOCALES:append = " en_US.UTF-8 es_US.UTF-8 en_GB.UTF-8"' >> ./conf/local.conf
          echo 'IMAGE_LINGUAS:append = " en-us en-gb es-us"' >> ./conf/local.conf
          echo 'DEFAULT_TIMEZONE = "America/Los_Angeles"' >> ./conf/local.conf
          echo 'PACKAGECONFIG:append:pn-ffmpeg = " openssl"' >> ./conf/local.conf
          echo 'PACKAGECONFIG:append:pn-weston = " remoting"' >> ./conf/local.conf
          echo 'IMAGE_INSTALL:append = "\
              default-language-en-us-utf8 \
              tzdata-americas \
              tzdata-core \
              flutter-auto-runtime${{ env.RUNTIME }} \
              flutter-pi-runtime${{ env.RUNTIME }} \
              flutter-gallery-runtime${{ env.RUNTIME }} \
              flutter-test-secure-storage-runtime${{ env.RUNTIME }} \
              flutter-test-video-player-runtime${{ env.RUNTIME }} \
              flutter-test-plugins-runtime${{ env.RUNTIME }} \
              flutter-test-texture-egl-runtime${{ env.RUNTIME }} \
              flutter-test-localization-runtime${{ env.RUNTIME }} \
              flutter-test-membrane-runtime${{ env.RUNTIME }} \
              flutter-test-frb-runtime${{ env.RUNTIME }} \
              "' >> ./conf/local.conf
          echo 'LICENSE_FLAGS_ACCEPTED += " commercial"' >> ./conf/local.conf
          echo '********** ./conf/local.conf **********'
          cat ./conf/local.conf
          echo '***************************************'
          bitbake-layers show-layers
          bitbake-layers remove-layer meta-flutter
          bitbake-layers add-layer ../../meta-flutter
          bitbake-layers show-layers
          echo '***************************************'
          bitbake -e virtual/kernel | grep "^PV"
          bitbake -e virtual/kernel | grep "^PN"
          echo '***************************************'
          bitbake -e rpi-image-flutter-wayland-${{ env.RUNTIME }} | grep "^DISTRO_FEATURES"
          bitbake -e rpi-image-flutter-wayland-${{ env.RUNTIME }} | grep "^IMAGE_FEATURES"
          echo '***************************************'
          bitbake -e > bb.environment
          bitbake -c do_cleansstate flutter-engine-runtime${{ env.RUNTIME }}
          bitbake -c do_cleansstate flutter-gallery-runtime${{ env.RUNTIME }}
          bitbake -c do_cleansstate flutter-test-plugins-runtime${{ env.RUNTIME }}
          bitbake -c do_cleansstate flutter-test-secure-storage-runtime${{ env.RUNTIME }}
          bitbake -c do_cleansstate flutter-test-texture-egl-runtime${{ env.RUNTIME }}
          bitbake -c do_cleansstate flutter-test-video-player-runtime${{ env.RUNTIME }}
          bitbake -c do_cleansstate flutter-test-localization-runtime${{ env.RUNTIME }}
          bitbake -c do_cleansstate membrane-example
          bitbake -c do_cleansstate membrane-example-native
          bitbake -c do_cleansstate flutter-test-membrane-runtime${{ env.RUNTIME }}
          bitbake -c do_cleansstate flutter-rust-bridge-example
          bitbake -c do_cleansstate flutter-test-frb-runtime${{ env.RUNTIME }}

      - name: Build rpi-image-weston-flutter-runtimeprofile
        shell: bash
        working-directory: ../zero2w-drm-kirkstone-latest
        run: |
          . ./sources/poky/oe-init-build-env ${{ env.MACHINE }}
          bitbake rpi-image-flutter-wayland-${{ env.RUNTIME }}
          rm -rf /home/dev/artifacts/*
          cp bb.environment /home/dev/artifacts
          cp tmp/deploy/images/raspberrypi0-2w-64/rpi-image-flutter-wayland-${{ env.RUNTIME }}-raspberrypi0-2w-64.wic.bmap /home/dev/artifacts
          cp tmp/deploy/images/raspberrypi0-2w-64/rpi-image-flutter-wayland-${{ env.RUNTIME }}-raspberrypi0-2w-64.wic.bz2 /home/dev/artifacts

      - name: Publish SD card image artifact
        uses: actions/upload-artifact@v2
        with:
          name: raspberrypi0-2w-64-weston-flutter-runtime${{ env.RUNTIME }}-sdimage
          path: |
             /home/dev/artifacts/*

  weston-debug:
  
    env:
      YOCTO_BRANCH: "kirkstone"
      MACHINE: raspberrypi0-2w-64
      RUNTIME: "debug"
      
    runs-on: [self-hosted, linux]
    
    container:
      image: ghcr.io/meta-flutter/ubuntu-20-dev:main
      options:
        --user 1018
        --storage-opt overlay.mount_program=/usr/bin/fuse-overlayfs
        --storage-opt overlay.mountopt=nodev,metacopy=on,noxattrs=1
        -v /mnt/raid10/github-ci/download:/home/dev/dl:Z
        -v /mnt/raid10/github-ci/sstate/yocto/kirkstone/zero2w-drm/latest:/home/dev/sstate:Z
        -v /mnt/raid10/github-ci/artifacts/zero2w/drm:/home/dev/artifacts:Z


    steps:
    
      - name: Display UID Info
        run: |
          whoami
          id -u
          
      - name: Set Ownership
        run: |
          chown -R dev:dev $HOME .
          
      - uses: actions/checkout@v2
        with:
          path: ''

      - name: Fetch poky
        run: |
          [ -d ../zero2w-drm-kirkstone-latest ] || mkdir -p ../zero2w-drm-kirkstone-latest
          cd ../zero2w-drm-kirkstone-latest
          rm -rf sources || true
          git config --global user.name "Joel Winarske"
          git config --global user.email joel@winarske@gmail.com
          /home/dev/bin/repo init -u https://github.com/jwinarske/manifests.git -m rpi64.xml -b $YOCTO_BRANCH
          /home/dev/bin/repo sync --force-sync --no-clone-bundle -j `grep -c ^processor /proc/cpuinfo` &
          wait

      - name: Configure build
        shell: bash
        working-directory: ../zero2w-drm-kirkstone-latest
        run: |
          rm -rf ${{ env.MACHINE }}/conf || true
          . ./setup-environment ${{ env.MACHINE }}
          echo '***************************************'
          echo 'DL_DIR = "/home/dev/dl"' >> ./conf/local.conf
          echo 'SSTATE_DIR = "/home/dev/sstate"' >> ./conf/local.conf
          echo 'SSTATE_MIRRORS = "file://.* file:///home/dev/sstate/PATH"' >> ./conf/local.conf
          echo 'ENABLE_BINARY_LOCALE_GENERATION = "1"' >> ./conf/local.conf
          echo 'GLIBC_GENERATE_LOCALES:append = " en_US.UTF-8 es_US.UTF-8 en_GB.UTF-8"' >> ./conf/local.conf
          echo 'IMAGE_LINGUAS:append = " en-us en-gb es-us"' >> ./conf/local.conf
          echo 'DEFAULT_TIMEZONE = "America/Los_Angeles"' >> ./conf/local.conf
          echo 'PACKAGECONFIG:append:pn-ffmpeg = " openssl"' >> ./conf/local.conf
          echo 'PACKAGECONFIG:append:pn-weston = " remoting"' >> ./conf/local.conf
          echo 'IMAGE_INSTALL:append = "\
              default-language-en-us-utf8 \
              tzdata-americas \
              tzdata-core \
              flutter-auto-runtime${{ env.RUNTIME }} \
              flutter-pi-runtime${{ env.RUNTIME }} \
              membrane-example \
              flutter-rust-bridge-example \
              "' >> ./conf/local.conf
          echo 'LICENSE_FLAGS_ACCEPTED += " commercial"' >> ./conf/local.conf
          echo '********** ./conf/local.conf **********'
          cat ./conf/local.conf
          echo '***************************************'
          bitbake-layers show-layers
          bitbake-layers remove-layer meta-flutter
          bitbake-layers add-layer ../../meta-flutter
          bitbake-layers show-layers
          echo '***************************************'
          bitbake -e virtual/kernel | grep "^PV"
          bitbake -e virtual/kernel | grep "^PN"
          echo '***************************************'
          bitbake -e rpi-image-flutter-wayland-${{ env.RUNTIME }} | grep "^DISTRO_FEATURES"
          bitbake -e rpi-image-flutter-wayland-${{ env.RUNTIME }} | grep "^IMAGE_FEATURES"
          echo '***************************************'
          bitbake -e > bb.environment
          bitbake -c do_cleansstate flutter-sdk-native
          bitbake -c do_cleansstate flutter-engine-runtime${{ env.RUNTIME }}
          bitbake -c do_cleansstate membrane-example
          bitbake -c do_cleansstate flutter-rust-bridge-example

      - name: Build rpi-image-flutter-wayland-debug
        shell: bash
        working-directory: ../zero2w-drm-kirkstone-latest
        run: |
          . ./sources/poky/oe-init-build-env ${{ env.MACHINE }}
          bitbake rpi-image-flutter-wayland-${{ env.RUNTIME }}
          rm -rf /home/dev/artifacts/*
          cp bb.environment /home/dev/artifacts
          cp tmp/deploy/images/raspberrypi0-2w-64/rpi-image-flutter-wayland-${{ env.RUNTIME }}-raspberrypi0-2w-64.wic.bmap /home/dev/artifacts
          cp tmp/deploy/images/raspberrypi0-2w-64/rpi-image-flutter-wayland-${{ env.RUNTIME }}-raspberrypi0-2w-64.wic.bz2 /home/dev/artifacts

      - name: Publish SD card image artifact
        uses: actions/upload-artifact@v2
        with:
          name: raspberrypi0-2w-64-weston-flutter-runtime${{ env.RUNTIME }}-sdimage
          path: |
             /home/dev/artifacts/*
