name: kirkstone-agl-renesas-m3

on:
  pull_request:
    types: [ opened, synchronize, reopened, closed ]
  release:
    types: [ published, created, edited ]
  workflow_dispatch:
  schedule:
    # daily
    - cron:  '0 0 * * *'

jobs:

  master-renesas-m3:
  
    env:
      MACHINE: m3ulcb
      AGL_BRANCH: master
      WORKSPACE: ../agl-master-renesas-m3
      XDG_DOWNLOAD_DIR: /home/dev/rcar_dl

    runs-on: [self-hosted, linux]
    
    container:
      image: ghcr.io/meta-flutter/ubuntu-18-dev:main
      options:
        --user 1018
        --storage-opt overlay.mount_program=/usr/bin/fuse-overlayfs
        --storage-opt overlay.mountopt=nodev,metacopy=on,noxattrs=1
        -v /mnt/raid10/github-ci/download:/home/dev/dl:Z
        -v /mnt/raid10/github-ci/sstate/agl/m3ulcb:/home/dev/sstate:Z
        -v /mnt/raid10/github-ci/artifacts/agl/m3ulcb:/home/dev/artifacts:Z
        -v /mnt/raid10/github-ci/rcar_dl:/home/dev/rcar_dl:Z

      
    steps:
    
      - name: Display UID Info
        run: |
          whoami
          id -u
          
      - name: Set Ownership
        run: |
          chown -R dev:dev $HOME .
          
      - uses: actions/checkout@v2

      - name: Fetch Layers
        run: |
          [ -d ${{ env.WORKSPACE }} ] || mkdir -p ${{ env.WORKSPACE }}
          cd ${{ env.WORKSPACE }}
          rm -rf .repo  bsp  external  meta-agl  meta-agl-demo  meta-agl-devel  meta-agl-flutter binary-tmp
          /home/dev/bin/repo init -b ${{ env.AGL_BRANCH }} -u https://gerrit.automotivelinux.org/gerrit/AGL/AGL-repo --no-clone-bundle
          /home/dev/bin/repo sync --no-clone-bundle -j `grep -c ^processor /proc/cpuinfo` &
          wait
          cd external
          rm -rf meta-flutter || true
          ln -sf ../../meta-flutter meta-flutter
          cd ..
          sed -i '/weston-ini-conf-landscape/d' meta-agl-devel/meta-agl-flutter/recipes-platform/images/agl-image-flutter-debug.bb
          sed -i '/weston-ini-conf-landscape/d' meta-agl-devel/meta-agl-flutter/recipes-platform/images/agl-image-flutter-profile.bb
          sed -i '/weston-ini-conf-landscape/d' meta-agl-devel/meta-agl-flutter/recipes-platform/images/agl-image-flutter.bb
          rm ./bsp/meta-rcar/meta-rcar-gen3-adas/recipes-bsp/u-boot/u-boot_2020.01.bbappend || true
          rm ./meta-agl/meta-agl-bsp/meta-rcar-gen3/recipes-bsp/u-boot/u-boot_2020.01.bbappend || true
          rm ./bsp/meta-renesas/meta-rcar-gen3/recipes-graphics/cogl/cogl-1.0_1.%.bbappend || true
          
      - name: Configure AGL build
        shell: bash
        working-directory: ${{ env.WORKSPACE }}
        run: |
          rm -rf build/conf
          . ./meta-agl/scripts/aglsetup.sh \
            -m ${{ env.MACHINE }} \
            agl-devel \
            agl-basesystem \
            agl-flutter
          echo '***************************************'
          echo 'INHERIT += "rm_work"' >> ./conf/local.conf
          echo 'DL_DIR = "/home/dev/dl"' >> ./conf/local.conf
          echo 'SSTATE_DIR = "/home/dev/sstate"' >> ./conf/local.conf
          echo 'SSTATE_MIRRORS = "file://.* file:///home/dev/sstate/PATH"' >> ./conf/local.conf
          echo 'SSTATE_MIRRORS += "file://.* http://download.automotivelinux.org/sstate-mirror/${{ env.AGL_BRANCH }}/${DEFAULTTUNE}/PATH;downloadfilename=PATH"' >> ./conf/local.conf
          echo 'INHERIT:remove = "uninative"' >> ./conf/local.conf
          echo 'INSANE_SKIP_${PN} += "host-user-contaminated"' >> ../external/meta-clang/recipes-devtools/clang/clang_git.bb
          echo 'INHIBIT_PACKAGE_DEBUG_SPLIT = "1"' >> ./conf/local.conf
          echo 'FLUTTER_SDK_TAG = "3.0.1"' >> ./conf/local.conf
          echo 'LICENSE_FLAGS_ACCEPTED += " commercial"' >> ./conf/local.conf
          echo '** Layers *****************************'
          sed -i 's|\${METADIR}/bsp/meta-renesas/meta-rcar-gen3 \\|\${METADIR}/bsp/meta-renesas/meta-rcar-gen3 \\\n  ${METADIR}/external/meta-openembedded/meta-python \\|g' conf/bblayers.conf
          bitbake-layers show-layers
          echo '** Kernel *****************************'
          bitbake -e virtual/kernel | grep "^PV"
          bitbake -e virtual/kernel | grep "^PN"
          echo '***************************************'
          bitbake -e > bb.environment
          echo '***************************************'
          bitbake ca-certificates -c do_cleansstate
          bitbake ca-certificates-native -c do_cleansstate
          bitbake flutter-sdk -c do_cleansstate
          bitbake flutter-sdk-native -c do_cleansstate
          bitbake flutter-engine-runtimedebug -c do_cleansstate
          bitbake flutter-engine-runtimerelease -c do_cleansstate
          bitbake flutter-engine-runtimeprofile -c do_cleansstate
          bitbake flutter-gallery-runtimedebug -c do_cleansstate
          bitbake flutter-gallery-runtimerelease -c do_cleansstate
          bitbake flutter-gallery-runtimeprofile -c do_cleansstate
          bitbake ivi-homescreen-runtimedebug -c do_cleansstate
          bitbake ivi-homescreen-runtimerelease -c do_cleansstate
          bitbake ivi-homescreen-runtimeprofile -c do_cleansstate

      - name: Build agl-image-flutter-debug
        shell: bash
        working-directory: ${{ env.WORKSPACE }}
        run: |
          . ./build/agl-init-build-env
          rm -rf /home/dev/artifacts/*
          bitbake agl-image-flutter-debug
          cp bb.environment /home/dev/artifacts
          cd tmp/deploy/images/${{ env.MACHINE }}
          cp agl-image-flutter-debug-m3ulcb-*.rootfs.wic.bmap /home/dev/artifacts
          cp agl-image-flutter-debug-m3ulcb-*.rootfs.wic.xz /home/dev/artifacts
          mkdir -p /home/dev/artifacts/boot
          cp bootparam_sa0.srec /home/dev/artifacts
          cp bl2-m3ulcb.srec /home/dev/artifacts
          cp cert_header_sa6.srec /home/dev/artifacts
          cp bl31-m3ulcb.srec /home/dev/artifacts
          cp tee-m3ulcb.srec /home/dev/artifacts
          cp u-boot-elf-m3ulcb-*.srec /home/dev/artifacts

      - name: Publish agl-image-flutter-runtimedebug artifacts
        uses: actions/upload-artifact@v2
        with:
          name: agl-image-flutter-runtimedebug-m3ulcb-linux
          path: |
             /home/dev/artifacts/*

      - name: Build agl-image-flutter-debug SDK
        shell: bash
        working-directory: ${{ env.WORKSPACE }}
        run: |
          . ./build/agl-init-build-env
          rm -rf /home/dev/artifacts/*
          bitbake agl-image-flutter-debug -c do_populate_sdk
          cp bb.environment /home/dev/artifacts
          cp tmp/deploy/sdk/poky-agl-glibc-*-agl-image-flutter-debug-*.sh /home/dev/artifacts

      - name: Publish agl-image-flutter-runtimedebug SDK artifact
        uses: actions/upload-artifact@v2
        with:
          name: agl-image-flutter-runtimedebug-sdk-m3ulcb-linux
          path: |
             /home/dev/artifacts/*
