name: kirkstone-rpi-zero2w-64

on:
  pull_request:
    types: [ opened, synchronize, reopened, closed ]
  release:
    types: [ published, created, edited ]
  workflow_dispatch:
  schedule:
    # daily
    - cron:  '0 0 * * *'

jobs:

  kirkstone-zero2w-weston:
  
    env:
      DISTRO_VERSION: "4.0"
      YOCTO_BRANCH: "kirkstone"
      MACHINE: raspberrypi0-2w-64
      FLUTTER_RUNTIME: "release"
      
    runs-on: [self-hosted, linux]
    
    container:
      image: ghcr.io/meta-flutter/ubuntu-20-dev:main
      options:
        --user 1018
        --storage-opt overlay.mount_program=/usr/bin/fuse-overlayfs
        --storage-opt overlay.mountopt=nodev,metacopy=on,noxattrs=1
        -v /mnt/raid10/github-ci/download:/home/dev/dl:Z
        -v /mnt/raid10/github-ci/sstate/yocto/kirkstone/zero2w-drm/latest:/home/dev/sstate:Z
        -v /mnt/raid10/github-ci/artifacts/zero2w/drm:/home/dev/artifacts:Z


    steps:
    
      - name: Display UID Info
        run: |
          whoami
          id -u
          
      - name: Set Ownership
        run: |
          chown -R dev:dev $HOME .
          
      - uses: actions/checkout@v2
        with:
          path: ''

      - name: Fetch poky
        run: |
          [ -d ../zero2w-drm-kirkstone-latest ] || mkdir -p ../zero2w-drm-kirkstone-latest
          cd ../zero2w-drm-kirkstone-latest
          rm -rf sources || true
          ls -la
          git config --list
          git config --global user.email joel@winarske@gmail.com
          git config --global user.name "Joel Winarske"
          git config --list
          /home/dev/bin/repo init -u https://github.com/jwinarske/manifests.git -m rpi64.xml -b $YOCTO_BRANCH
          /home/dev/bin/repo sync --force-sync --no-clone-bundle -j `grep -c ^processor /proc/cpuinfo` &
          wait

      - name: Configure build
        shell: bash
        working-directory: ../zero2w-drm-kirkstone-latest
        run: |
          rm -rf ${{ env.MACHINE }}/conf || true
          . ./setup-environment ${{ env.MACHINE }}
          echo '***************************************'
          echo 'DL_DIR = "/home/dev/dl"' >> ./conf/local.conf
          echo 'SSTATE_DIR = "/home/dev/sstate"' >> ./conf/local.conf
          echo 'SSTATE_MIRRORS = "file://.* file:///home/dev/sstate/PATH"' >> ./conf/local.conf
          echo 'SSTATE_MIRRORS += "file://.* http://sstate.yoctoproject.org/${{ env.DISTRO_VERSION }}/PATH;downloadfilename=PATH"' >> ./conf/local.conf
          echo 'ENABLE_BINARY_LOCALE_GENERATION = "1"' >> ./conf/local.conf
          echo 'GLIBC_GENERATE_LOCALES:append = " en_US.UTF-8 es_US.UTF-8 en_GB.UTF-8"' >> ./conf/local.conf
          echo 'IMAGE_LINGUAS:append = " en-us en-gb es-us"' >> ./conf/local.conf
          echo 'DEFAULT_TIMEZONE = "America/Los_Angeles"' >> ./conf/local.conf
          echo 'PREFERRED_PROVIDER:libserialport = "6f9b03e"' >> ./conf/local.conf
          echo 'IMAGE_FEATURES:remove = "splash"' >> ./conf/local.conf
          echo 'RDEPENDS_packagegroup-rpi-test:remove = "connman connman-client"' >> ./conf/local.conf
          echo '********** ./conf/local.conf **********'
          cat ./conf/local.conf
          echo '***************************************'
          bitbake-layers remove-layer meta-flutter
          bitbake-layers add-layer ../../meta-flutter
          bitbake-layers show-layers
          echo '***************************************'
          bitbake -e virtual/kernel | grep "^PV"
          bitbake -e virtual/kernel | grep "^PN"
          echo '***************************************'
          bitbake -e rpi-test-image | grep "^DISTRO_FEATURES"
          bitbake -e rpi-test-image | grep "^IMAGE_FEATURES"
          echo '***************************************'
          bitbake -e > bb.environment

      - name: Build rpi-test-image
        shell: bash
        working-directory: ../zero2w-drm-kirkstone-latest
        run: |
          . ./sources/poky/oe-init-build-env ${{ env.MACHINE }}
          bitbake rpi-test-image

      - name: Build flutter-engine
        shell: bash
        working-directory: ../zero2w-drm-kirkstone-latest
        run: |
          . ./sources/poky/oe-init-build-env ${{ env.MACHINE }}
          bitbake flutter-engine-${{ env.FLUTTER_RUNTIME }} -c do_cleansstate
          bitbake flutter-engine-${{ env.FLUTTER_RUNTIME }}
          rm -rf /home/dev/artifacts/*
          cp tmp/deploy/rpm/cortexa53/flutter-engine-${{ env.FLUTTER_RUNTIME }}-git*.rpm /home/dev/artifacts

      - name: Publish flutter-engine artifacts
        uses: actions/upload-artifact@v2
        with:
          name: flutter-engine-${{ env.FLUTTER_RUNTIME }}-zero2w-64
          path: |
             /home/dev/artifacts/*.rpm

      - name: Build flutter-pi
        shell: bash
        working-directory: ../zero2w-drm-kirkstone-latest
        run: |
          . ./sources/poky/oe-init-build-env ${{ env.MACHINE }}
          bitbake flutter-pi-${{ env.FLUTTER_RUNTIME }}
          rm -rf /home/dev/artifacts/*
          cp tmp/deploy/rpm/cortexa53/flutter-pi-${{ env.FLUTTER_RUNTIME }}-git*.rpm /home/dev/artifacts

      - name: Publish flutter-pi artifacts
        uses: actions/upload-artifact@v2
        with:
          name: flutter-pi-${{ env.FLUTTER_RUNTIME }}-zero2w-64
          path: |
             /home/dev/artifacts/*.rpm

      - name: Build flutter-gallery
        shell: bash
        working-directory: ../zero2w-drm-kirkstone-latest
        run: |
          . ./sources/poky/oe-init-build-env ${{ env.MACHINE }}
          bitbake flutter-sdk-native -c do_cleansstate
          bitbake flutter-gallery-${{ env.FLUTTER_RUNTIME }} -c do_cleansstate
          bitbake flutter-gallery-${{ env.FLUTTER_RUNTIME }}
          rm -rf /home/dev/artifacts/*
          cp tmp/deploy/rpm/cortexa53/flutter-gallery-${{ env.FLUTTER_RUNTIME }}-git*.rpm /home/dev/artifacts

      - name: Publish flutter-gallery artifacts
        uses: actions/upload-artifact@v2
        with:
          name: flutter-gallery-${{ env.FLUTTER_RUNTIME }}-zero2w-64
          path: |
             /home/dev/artifacts/*.rpm

      - name: Build rpi-test-image
        shell: bash
        working-directory: ../zero2w-drm-kirkstone-latest
        run: |
          . ./sources/poky/oe-init-build-env ${{ env.MACHINE }}
          echo 'IMAGE_INSTALL:append = " \
              adwaita-icon-theme-cursors \
              default-language-en-us-utf8 \
              flutter-engine-${{ env.FLUTTER_RUNTIME }} \
              flutter-gallery-${{ env.FLUTTER_RUNTIME }} \
              flutter-linux-plugins-${{ env.FLUTTER_RUNTIME }} \
              flutter-pi-${{ env.FLUTTER_RUNTIME }} \
              geoclue \
              gsettings-desktop-schemas \
              gstreamer1.0-libav \
              gstreamer1.0-plugins-bad \
              gstreamer1.0-plugins-good \
              gstreamer1.0-plugins-ugly \
              ivi-homescreen-${{ env.FLUTTER_RUNTIME }} \
              liberation-fonts \
              libgpiod \
              libserialport \
              networkmanager \
              os-release \
              tzdata-americas \
              tzdata-core \
              upower \
              xdg-user-dirs \
              xkeyboard-config \
              "' >> ./conf/local.conf
          bitbake rpi-test-image
          rm -rf /home/dev/artifacts/*
          cp bb.environment /home/dev/artifacts
          cp tmp/deploy/images/raspberrypi0-2w-64/rpi-test-image-raspberrypi0-2w-64.wic.bmap /home/dev/artifacts
          cp tmp/deploy/images/raspberrypi0-2w-64/rpi-test-image-raspberrypi0-2w-64.wic.bz2 /home/dev/artifacts

      - name: Publish SD card image artifact
        uses: actions/upload-artifact@v2
        with:
          name: zero2w-rpi-test-flutter-${{ env.FLUTTER_RUNTIME }}-kirkstone-sdimage
          path: |
             /home/dev/artifacts/*
