name: rpi4-32

on:
  pull_request:
    types: [ opened, synchronize, reopened, closed ]
  release:
    types: [ published, created, edited ]
  workflow_dispatch:
  schedule:
    # daily
    - cron:  '0 0 * * *'

jobs:

  honister-rpi4-drm:
  
    env:
      DISTRO_VERSION: 3.4
      YOCTO_BRANCH: honister
      MACHINE: raspberrypi4
      
    runs-on: [self-hosted, linux]
    
    container:
      image: ghcr.io/meta-flutter/ubuntu-20-dev:main
      options:
        --user 1018
        --storage-opt overlay.mount_program=/usr/bin/fuse-overlayfs
        --storage-opt overlay.mountopt=nodev,metacopy=on,noxattrs=1
        -v /b/github-ci/download:/home/dev/dl:Z
        -v /b/github-ci/sstate/yocto/honister/rpi4-32-drm/latest:/home/dev/sstate:Z
        -v /b/github-ci/artifacts/rpi4-32/drm:/home/dev/artifacts:Z


    steps:
    
      - name: Display UID Info
        run: |
          whoami
          id -u
          
      - name: Set Ownership
        run: |
          chown -R dev:dev $HOME .
          
      - uses: actions/checkout@v2
        with:
          path: ''

      - name: Fetch poky
        run: |
          [ -d ../rpi4-32-drm-honister-latest ] || mkdir -p ../rpi4-32-drm-honister-latest
          cd ../rpi4-32-drm-honister-latest
          pwd
          ls -la
          git config --list
          git config --global user.email joel@winarske@gmail.com
          git config --global user.name "Joel Winarske"
          git config --list
          /home/dev/bin/repo init -u https://github.com/jwinarske/manifests.git -m rpi64.xml -b $YOCTO_BRANCH
          /home/dev/bin/repo sync --force-sync --no-clone-bundle -j `grep -c ^processor /proc/cpuinfo` &
          wait
          cd sources/poky
          git reset --hard
          git checkout honister
          git checkout honister-3.4
          git apply ../../conf/rpi64/0001-mesa-broadcom-vulkan.patch && cd ../..
          cd sources/meta-raspberrypi
          git reset --hard
          git checkout master
          git apply ../../conf/rpi64/0001-rpi-mesa-vulkan-broadcom-override.patch && cd ../..

      - name: Configure build
        shell: bash
        working-directory: ../rpi4-32-drm-honister-latest
        run: |
          rm -rf ${{ env.MACHINE }} || true
          . ./setup-environment ${{ env.MACHINE }}
          echo '***************************************'
          echo 'DL_DIR = "/home/dev/dl"' >> ./conf/local.conf
          echo 'SSTATE_DIR = "/home/dev/sstate"' >> ./conf/local.conf
          echo 'SSTATE_MIRRORS = "file://.* file:///home/dev/sstate/PATH"' >> ./conf/local.conf
          echo 'SSTATE_MIRRORS += "file://.* http://sstate.yoctoproject.org/${{ env.DISTRO_VERSION }}/PATH;downloadfilename=PATH"' >> ./conf/local.conf
          echo 'FLUTTER_CHANNEL = "master"' >> ./conf/local.conf
          echo 'PACKAGECONFIG:pn-flutter-engine = "embedder-for-target disable-desktop-embeddings fontconfig mode-release"' >> ./conf/local.conf
          echo 'TARGET_GCC_VERSION = "11.2.0"' >> ./conf/local.conf
          echo 'PACKAGECONFIG:pn-sascha-samples = "d2d"' >> ./conf/local.conf
          echo '********** ./conf/local.conf **********'
          cat ./conf/local.conf
          echo '***************************************'
          bitbake-layers show-layers
          echo '***************************************'
          bitbake -e virtual/kernel | grep "^PV"
          bitbake -e virtual/kernel | grep "^PN"
          echo '***************************************'
          bitbake -e core-image-minimal | grep "^DISTRO_FEATURES"
          echo '***************************************'
          bitbake -e > bb.environment

      - name: Build core-image-minimal
        shell: bash
        working-directory: ../rpi4-32-drm-honister-latest
        run: |
          . ./sources/poky/oe-init-build-env ${{ env.MACHINE }}
          bitbake core-image-minimal
          rm -rf /home/dev/artifacts/*
          cp tmp/deploy/rpm/cortexa7t2hf_neon_vfpv4/mesa-vulkan-drivers-*.rpm /home/dev/artifacts

      - name: Publish mesa-vulkan-drivers artifacts
        uses: actions/upload-artifact@v2
        with:
          name: mesa-vulkan-drivers-rpi4
          path: |
             /home/dev/artifacts/*.rpm

      - name: Build sascha-samples (D2D)
        shell: bash
        working-directory: ../rpi4-32-drm-honister-latest
        run: |
          . ./sources/poky/oe-init-build-env ${{ env.MACHINE }}
          bitbake sascha-samples -c do_cleansstate
          bitbake sascha-samples
          rm -rf /home/dev/artifacts/*
          cp tmp/deploy/rpm/cortexa7t2hf_neon_vfpv4/sascha-samples-git*.rpm /home/dev/artifacts

      - name: Publish sascha-samples artifacts
        uses: actions/upload-artifact@v2
        with:
          name: sascha-samples-d2d-rpi4
          path: |
             /home/dev/artifacts/*.rpm

      - name: Build flutter-engine
        shell: bash
        working-directory: ../rpi4-32-drm-honister-latest
        run: |
          . ./sources/poky/oe-init-build-env ${{ env.MACHINE }}
          bitbake flutter-engine -c do_cleansstate
          bitbake flutter-engine
          rm -rf /home/dev/artifacts/*
          cp tmp/deploy/rpm/cortexa7t2hf_neon_vfpv4/flutter-engine-git*.rpm /home/dev/artifacts

      - name: Publish flutter-engine artifacts
        uses: actions/upload-artifact@v2
        with:
          name: flutter-engine-rpi4
          path: |
             /home/dev/artifacts/*.rpm

      - name: Build flutter-pi
        shell: bash
        working-directory: ../rpi4-32-drm-honister-latest
        run: |
          . ./sources/poky/oe-init-build-env ${{ env.MACHINE }}
          bitbake flutter-pi -c do_cleansstate
          bitbake flutter-pi
          rm -rf /home/dev/artifacts/*
          cp tmp/deploy/rpm/cortexa7t2hf_neon_vfpv4/flutter-pi-git*.rpm /home/dev/artifacts

      - name: Publish flutter-pi artifacts
        uses: actions/upload-artifact@v2
        with:
          name: flutter-pi-rpi4
          path: |
             /home/dev/artifacts/*.rpm

      - name: Build flutter-gallery
        shell: bash
        working-directory: ../rpi4-32-drm-honister-latest
        run: |
          . ./sources/poky/oe-init-build-env ${{ env.MACHINE }}
          bitbake flutter-sdk-native -c do_cleansstate
          bitbake flutter-gallery -c do_cleansstate
          bitbake flutter-gallery
          rm -rf /home/dev/artifacts/*
          cp tmp/deploy/rpm/cortexa7t2hf_neon_vfpv4/flutter-gallery-git*.rpm /home/dev/artifacts

      - name: Publish flutter-gallery artifacts
        uses: actions/upload-artifact@v2
        with:
          name: flutter-gallery-rpi4
          path: |
             /home/dev/artifacts/*.rpm

      - name: Build core-image-minimal
        shell: bash
        working-directory: ../rpi4-32-drm-honister-latest
        run: |
          . ./sources/poky/oe-init-build-env ${{ env.MACHINE }}
          echo 'CORE_IMAGE_EXTRA_INSTALL:append = " flutter-pi"' >> ./conf/local.conf
          echo 'CORE_IMAGE_EXTRA_INSTALL:append = " flutter-gallery"' >> ./conf/local.conf
          echo 'CORE_IMAGE_EXTRA_INSTALL:append = " sascha-samples"' >> ./conf/local.conf
          echo 'CORE_IMAGE_EXTRA_INSTALL:append = " vkquake3"' >> ./conf/local.conf
          echo 'CORE_IMAGE_EXTRA_INSTALL:append = " vkrunner"' >> ./conf/local.conf
          bitbake core-image-minimal
          rm -rf /home/dev/artifacts/*
          cp bb.environment /home/dev/artifacts
          cp tmp/deploy/images/raspberrypi4/core-image-minimal-raspberrypi4.wic.bmap /home/dev/artifacts
          cp tmp/deploy/images/raspberrypi4/core-image-minimal-raspberrypi4.wic.bz2 /home/dev/artifacts

      - name: Publish SD card image artifact
        uses: actions/upload-artifact@v2
        with:
          name: rpi4-drm-honister-sdimage
          path: |
             /home/dev/artifacts/*
